## Creación de arrays - Fundamentos

In [1]:
# Celda de imports
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.4


In [2]:
# Arrays básicos
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Array 1D:", arr_1d)
print("Array 2D:\n", arr_2d)
print("Array 3D shape:", arr_3d.shape)

# Funciones de creación útiles
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identity = np.eye(3)
random_vals = np.random.random((2, 3))

print("\nZeros 3x4:\n", zeros)
print("\nIdentidad 3x3:\n", identity)

# Rangos y secuencias
range_arr = np.arange(0, 10, 2)  # inicio, fin, paso
linspace_arr = np.linspace(0, 1, 5)  # inicio, fin, cantidad

print("\nArange:", range_arr)
print("Linspace:", linspace_arr)

Array 1D: [1 2 3 4 5]
Array 2D:
 [[1 2 3]
 [4 5 6]]
Array 3D shape: (2, 2, 2)

Zeros 3x4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Identidad 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


## Propiedades de los arrays

In [3]:
data = np.random.randint(0, 100, (4, 5))
print("Array ejemplo:\n", data)
print(f"Shape: {data.shape}")
print(f"Dimensiones: {data.ndim}")
print(f"Tamaño total: {data.size}")
print(f"Tipo de datos: {data.dtype}")
print(f"Bytes por elemento: {data.itemsize}")

Array ejemplo:
 [[ 3 16 92 90 17]
 [25 15 23 94 91]
 [56 28 59 76 38]
 [10 67 99  9 55]]
Shape: (4, 5)
Dimensiones: 2
Tamaño total: 20
Tipo de datos: int64
Bytes por elemento: 8


## Indexado y slice

In [4]:
arr = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9],
               [10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19]])
print("Array base:\n", arr)

# Indexing básico
print("\nElemento [1,2]:", arr[1, 2])
print("Primera fila:", arr[0, :])
print("Segunda columna:", arr[:, 1])

# Slicing avanzado
print("\nPrimeras 2 filas, columnas 1-3:\n", arr[:2, 1:4])
print("Cada segunda fila:\n", arr[::2, :])

# Boolean indexing
mask = arr > 10
print("\nElementos > 10:", arr[mask])

# Fancy indexing
indices = [0, 2, 3]
print("Filas seleccionadas [0,2,3]:\n", arr[indices, :])

Array base:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Elemento [1,2]: 7
Primera fila: [0 1 2 3 4]
Segunda columna: [ 1  6 11 16]

Primeras 2 filas, columnas 1-3:
 [[1 2 3]
 [6 7 8]]
Cada segunda fila:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]

Elementos > 10: [11 12 13 14 15 16 17 18 19]
Filas seleccionadas [0,2,3]:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Reshape y manipulaciones de forma

In [5]:
original = np.arange(12) # vector del 0 al 11
print("Original:", original)

# Reshape
reshaped = original.reshape(3, 4)
print("Reshape 3x4 del vector original:\n", reshaped)

# Flatten
flattened = reshaped.flatten()
print("Flatten de la matriz reshaped:", flattened)

# Transpose
transposed = reshaped.T
print("Matriz transpuesta:\n", transposed)

# Concatenación
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

concat_v = np.vstack([arr1, arr2])  # vertical
concat_h = np.hstack([arr1, arr2])  # horizontal

print("\nConcatenación vertical:\n", concat_v)
print("Concatenación horizontal:\n", concat_h)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape 3x4 del vector original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten de la matriz reshaped: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz transpuesta:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Concatenación vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenación horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


## Broadcasting

In [ ]:
# Broadcasting básico
arr = np.array([[1, 2, 3], [4, 5, 6]])
k = 10

print("Array original:\n", arr)
print("\nArray + 10:\n", arr + k)

# Broadcasting con arrays
row_vector = np.array([1, 2, 3])
col_vector = np.array([[10],
                       [20]])

print("\nRow vector:", row_vector)
print("Col vector:\n", col_vector)
print("Broadcasting sum:\n", row_vector + col_vector)

## Operaciones aritméticas

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a =", a)
print("b =", b)

# Operaciones elemento a elemento
print("\nSuma:", a + b)
print("Multiplicación:", a * b)
print("Potencia:", a**2)

# Operaciones matriciales
matrix_a = np.array([[1, 2],
                     [3, 4]])
matrix_b = np.array([[5, 6],
                     [7, 8]])

print("\nMatriz A:\n", matrix_a)
print("Matriz B:\n", matrix_b)
print("Producto matricial A @ B:\n", matrix_a @ matrix_b)

# Funciones
x = np.linspace(0, 2 * np.pi, 17) # vector linealmente espaciado entre 0 y 2pi, 9 elementos
print("\nSeno de x:", np.sin(x))
print("\nSeno de x:", np.round(np.sin(x), 2))
print("\nExponencial:", np.exp([1, 2, 3]))

## Operaciones estadísticas

In [ ]:
data = np.random.normal(50, 15, 100)  # media=50, std=15, 100 elementos

print(f"Media: {np.mean(data):.2f}")
print(f"Mediana: {np.median(data):.2f}")
print(f"Desviación estándar: {np.std(data):.2f}")
print(f"Mínimo: {np.min(data):.2f}")
print(f"Máximo: {np.max(data):.2f}")

# Agregaciones por eje
matrix = np.random.randint(1, 10, (3, 4)) # random entre 1 y 10, tamaño 3x4
print("\nMatriz:\n", matrix)
print("Suma por filas (axis=1):", np.sum(matrix, axis=1))
print("Media por columnas (axis=0):", np.mean(matrix, axis=0))

## Sistemas de ecuaciones lineales

In [ ]:
# Sistema de ecuaciones lineal => ecuación matricial AX = B

# Por ejemplo:
# 3x + 2y + z = 1
# 5x + 3y + 4z = 2
# x + y - z = 1

A = np.array([[3, 2, 1],
              [5, 3, 4],
              [1, 1, -1]])
B = np.array([1,
              2,
              1])

X = np.linalg.solve(A, B)
print("Solución >", X)

Solución >  [-4.  6.  1.]


## Comparación de performance

In [ ]:
# Comparación de performance
import time

# Lista de Python vs NumPy array
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

# Suma con listas
start = time.time()
sum_list = sum(python_list)
time_list = time.time() - start

# Suma con NumPy
start = time.time()
sum_numpy = np.sum(numpy_array)
time_numpy = time.time() - start

print(f"Suma con listas Python: {time_list:.4f} segundos")
print(f"Suma con NumPy: {time_numpy:.4f} segundos")
print(f"NumPy es {time_list/time_numpy:.1f}x más rápido")

# Copia vs vista
original = np.arange(10)
view = original[::2]  # vista
copy = original[::2].copy()  # copia

print("\nOriginal:", original)
original[0] = 999
print("Después de modificar original[0]:")
print("Vista:", view)  # cambia porque es vista
print("Copia:", copy)  # no cambia porque es copia independiente

Suma con listas Python: 0.0074 segundos
Suma con NumPy: 0.0009 segundos
NumPy es 8.5x más rápido

Original: [0 1 2 3 4 5 6 7 8 9]
Después de modificar original[0]:
Vista: [999   2   4   6   8]
Copia: [0 2 4 6 8]
